spring.application.name=synex-api-gateway-service
server.port=8080

management.endpoints.web.exposure.include=health,info,env

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${OAUTH2_AUDIENCE}
